// <auto-generated />
using System;
using BlazorAppClientServer.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppClientServer.Server.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20241122185651_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Faktura", b =>
                {
                    b.Property<int>("FakturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FakturaId"));

                    b.Property<int?>("OrdreId")
                        .HasColumnType("int");

                    b.HasKey("FakturaId");

                    b.HasIndex("OrdreId");

                    b.ToTable("Fakturaer");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.KontorDame", b =>
                {
                    b.Property<int>("KontorDameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KontorDameId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KontorDameId");

                    b.ToTable("KontorDamer");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Kunde", b =>
                {
                    b.Property<int>("KundeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundeId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MekanikerId")
                        .HasColumnType("int");

                    b.Property<int?>("MærkeId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelefonNummer")
                        .HasColumnType("int");

                    b.HasKey("KundeId");

                    b.HasIndex("MekanikerId");

                    b.HasIndex("MærkeId");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Mekaniker", b =>
                {
                    b.Property<int>("MekanikerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MekanikerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MekanikerId");

                    b.ToTable("Mekanikers");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Mærke", b =>
                {
                    b.Property<int>("MærkeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MærkeId"));

                    b.Property<int?>("MekanikerId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MærkeId");

                    b.HasIndex("MekanikerId");

                    b.ToTable("Mærker");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Ordre", b =>
                {
                    b.Property<int>("OrdreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdreId"));

                    b.Property<int?>("KundeId")
                        .HasColumnType("int");

                    b.Property<int?>("MekanikerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrdreDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("OrdreId");

                    b.HasIndex("KundeId");

                    b.HasIndex("MekanikerId");

                    b.ToTable("Ordrer");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.OrdreYdelse", b =>
                {
                    b.Property<int>("OrdrerYdelseId")
                        .HasColumnType("int");

                    b.Property<int>("YdelseOrdrerId")
                        .HasColumnType("int");

                    b.Property<int>("Mængde")
                        .HasColumnType("int");

                    b.HasKey("OrdrerYdelseId", "YdelseOrdrerId");

                    b.HasIndex("YdelseOrdrerId");

                    b.ToTable("OrdreYdelser");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Værkfører", b =>
                {
                    b.Property<int>("VærkførerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VærkførerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VærkførerId");

                    b.ToTable("Værkførers");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Ydelse", b =>
                {
                    b.Property<int>("YdelseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YdelseId"));

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pris")
                        .HasColumnType("float");

                    b.Property<double>("Timer")
                        .HasColumnType("float");

                    b.HasKey("YdelseId");

                    b.ToTable("Ydelser");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Faktura", b =>
                {
                    b.HasOne("BlazorAppClientServer.Shared.Models.Ordre", "Ordre")
                        .WithMany()
                        .HasForeignKey("OrdreId");

                    b.Navigation("Ordre");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Kunde", b =>
                {
                    b.HasOne("BlazorAppClientServer.Shared.Models.Mekaniker", "Mekaniker")
                        .WithMany()
                        .HasForeignKey("MekanikerId");

                    b.HasOne("BlazorAppClientServer.Shared.Models.Mærke", "Mærke")
                        .WithMany()
                        .HasForeignKey("MærkeId");

                    b.Navigation("Mekaniker");

                    b.Navigation("Mærke");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Mærke", b =>
                {
                    b.HasOne("BlazorAppClientServer.Shared.Models.Mekaniker", "Mekaniker")
                        .WithMany("MærkeListe")
                        .HasForeignKey("MekanikerId");

                    b.Navigation("Mekaniker");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Ordre", b =>
                {
                    b.HasOne("BlazorAppClientServer.Shared.Models.Kunde", "Kunde")
                        .WithMany()
                        .HasForeignKey("KundeId");

                    b.HasOne("BlazorAppClientServer.Shared.Models.Mekaniker", "Mekaniker")
                        .WithMany("OrdreListe")
                        .HasForeignKey("MekanikerId");

                    b.Navigation("Kunde");

                    b.Navigation("Mekaniker");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.OrdreYdelse", b =>
                {
                    b.HasOne("BlazorAppClientServer.Shared.Models.Ordre", "Ordre")
                        .WithMany("OrdreYdelser")
                        .HasForeignKey("OrdrerYdelseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAppClientServer.Shared.Models.Ydelse", "Ydelse")
                        .WithMany("OrdreYdelser")
                        .HasForeignKey("YdelseOrdrerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordre");

                    b.Navigation("Ydelse");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Mekaniker", b =>
                {
                    b.Navigation("MærkeListe");

                    b.Navigation("OrdreListe");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Ordre", b =>
                {
                    b.Navigation("OrdreYdelser");
                });

            modelBuilder.Entity("BlazorAppClientServer.Shared.Models.Ydelse", b =>
                {
                    b.Navigation("OrdreYdelser");
                });
#pragma warning restore 612, 618
        }
    }
}
